# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/profkom/ROSS/ROSS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/profkom/ROSS/ROSS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/user/profkom/ROSS/ROSS && $(CMAKE_COMMAND) -E cmake_progress_start /home/user/profkom/ROSS/ROSS/CMakeFiles /home/user/profkom/ROSS/ROSS/models/template-model/CMakeFiles/progress.marks
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f CMakeFiles/Makefile2 models/template-model/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/profkom/ROSS/ROSS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f CMakeFiles/Makefile2 models/template-model/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f CMakeFiles/Makefile2 models/template-model/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f CMakeFiles/Makefile2 models/template-model/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/user/profkom/ROSS/ROSS && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
models/template-model/CMakeFiles/model.dir/rule:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f CMakeFiles/Makefile2 models/template-model/CMakeFiles/model.dir/rule
.PHONY : models/template-model/CMakeFiles/model.dir/rule

# Convenience name for target.
model: models/template-model/CMakeFiles/model.dir/rule

.PHONY : model

# fast build rule for target.
model/fast:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/build
.PHONY : model/fast

model_driver.o: model_driver.c.o

.PHONY : model_driver.o

# target to build an object file
model_driver.c.o:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/model_driver.c.o
.PHONY : model_driver.c.o

model_driver.i: model_driver.c.i

.PHONY : model_driver.i

# target to preprocess a source file
model_driver.c.i:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/model_driver.c.i
.PHONY : model_driver.c.i

model_driver.s: model_driver.c.s

.PHONY : model_driver.s

# target to generate assembly for a file
model_driver.c.s:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/model_driver.c.s
.PHONY : model_driver.c.s

model_main.o: model_main.c.o

.PHONY : model_main.o

# target to build an object file
model_main.c.o:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/model_main.c.o
.PHONY : model_main.c.o

model_main.i: model_main.c.i

.PHONY : model_main.i

# target to preprocess a source file
model_main.c.i:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/model_main.c.i
.PHONY : model_main.c.i

model_main.s: model_main.c.s

.PHONY : model_main.s

# target to generate assembly for a file
model_main.c.s:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/model_main.c.s
.PHONY : model_main.c.s

model_map.o: model_map.c.o

.PHONY : model_map.o

# target to build an object file
model_map.c.o:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/model_map.c.o
.PHONY : model_map.c.o

model_map.i: model_map.c.i

.PHONY : model_map.i

# target to preprocess a source file
model_map.c.i:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/model_map.c.i
.PHONY : model_map.c.i

model_map.s: model_map.c.s

.PHONY : model_map.s

# target to generate assembly for a file
model_map.c.s:
	cd /home/user/profkom/ROSS/ROSS && $(MAKE) -f models/template-model/CMakeFiles/model.dir/build.make models/template-model/CMakeFiles/model.dir/model_map.c.s
.PHONY : model_map.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... model"
	@echo "... model_driver.o"
	@echo "... model_driver.i"
	@echo "... model_driver.s"
	@echo "... model_main.o"
	@echo "... model_main.i"
	@echo "... model_main.s"
	@echo "... model_map.o"
	@echo "... model_map.i"
	@echo "... model_map.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/user/profkom/ROSS/ROSS && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

